version: "3.8"
services:
  localnet:
    image: "solanalabs/solana:stable"
    ports:
      - "8899:8899"
      - "8900:8900"
      - "9900:9900"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
