# Stage 1 - Build the base
FROM node:18-alpine AS base
WORKDIR /chat-server
COPY ./chat-server .
RUN yarn install

WORKDIR /grpc
COPY ./grpc .
RUN yarn install
RUN yarn proto-loader-gen-types --grpcLib=@grpc/grpc-js --outDir=src/proto/ src/proto/*.proto

# Stage 2 - Build the app
FROM base AS build
WORKDIR /grpc
RUN yarn build

WORKDIR /chat-server
RUN yarn build

# Stage 3 - Production
FROM build
WORKDIR /chat-server

CMD ["node", "dist/index.js"]