[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contracts = "2WU9NRgMxVsFCt1B2V9btRsXDXg1QoqfAbqqnJVFVDFU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jaredchilders/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
